puts "Enabling telemetry output"
cmd("CFS TO_OUTPUT_ENABLE with CCSDS_STREAMID 6272, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 17, CCSDS_CHECKSUM 0, CCSDS_FC 6, DEST_IP '127.0.0.1'")
wait(5)

puts "Turning ON WISE SBC"
cmd("CFS WISE_POWER_SBC with CCSDS_STREAMID 6348, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 1, CCSDS_CHECKSUM 0, CCSDS_FC 7")
wait(5)

puts "Resting Louver A count"
cmd("CFS THERM_RST_LVR_CNT_CC with CCSDS_STREAMID 6336, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 2, CCSDS_CHECKSUM 0, CCSDS_FC 2, LVR_SIDE 0")
wait(2)

puts "Resting Louver B count"
cmd("CFS THERM_RST_LVR_CNT_CC with CCSDS_STREAMID 6336, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 2, CCSDS_CHECKSUM 0, CCSDS_FC 2, LVR_SIDE 1")
wait(2)

loop do
  if (tlm_variable("CFS CFE_WISE_HKMSG WISE_CAP_A_CHRG", :CONVERTED) > 70.0)
    puts "Starting Observation"
    cmd("CFS WISE_OBS_START with CCSDS_STREAMID 6348, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 1, CCSDS_CHECKSUM 0, CCSDS_FC 5")
  end  
  
  if (tlm_variable("CFS CFE_WISE_HKMSG WISE_CAP_B_CHRG", :CONVERTED) > 50.0)
    puts "Discharging Capacitor B"
    cmd("CFS WISE_CAP_DISCHARGE with CCSDS_STREAMID 6348, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 2, CCSDS_CHECKSUM 0, CCSDS_FC 2, CAPACITOR CAP_B")
  end

  if (tlm_variable("CFS CFE_WISE_HKMSG WISE_CAP_C_CHRG", :CONVERTED) > 50.0)
    puts "Discharging Capacitor C"
    cmd("CFS WISE_CAP_DISCHARGE with CCSDS_STREAMID 6348, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 2, CCSDS_CHECKSUM 0, CCSDS_FC 2, CAPACITOR CAP_C")
  end  
  
  wait(2)
end
